imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

assetic:
    use_controller: "%use_assetic_controller%"
    node: "%assetic.node.bin%"
    filters:
        uglifyjs2:
            bin: "%assetic.uglifyjs.bin%"
            compress: true
        uglifycss:
            bin: "%assetic.uglifycss.bin%"
